version: '3'

services: 
    sandbox_api:
        container_name: sandbox
        build: .
        volumes: 
        - .:/usr/src/app
        - /usr/src/app/node_modules
        ports: 
            - 7003:80
        env_file: 
            - ./env