branch-defaults:
  master:
    environments: SandboxEbApi-env
global:
  application_name: sandbox-eb-api
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  repository: null
  sc: git
  workspace_type: Application
